# Generated by Django 3.1.3 on 2020-11-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercial_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos_name', models.CharField(max_length=255)),
                ('productos_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_comercial', to='productos.comercial')),
                ('productos_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_title', to='productos.title')),
            ],
        ),
    ]
